name: cicd-google-vm
env:
  ID_RSA: ${{ vars.ID_RSA}}
  SERVER_USER: ${{ vars.SERVER_USER }}
  SERVER_IP: ${{ vars.SERVER_IP }}
  REPOSITORY: ${{ vars.REPOSITORY }}

run-name: ${{ github.actor }} CICD
on: [push]
jobs:
  build-strapi-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/$REPOSITORY:latest .

      - name: Push Docker Hub
        run: docker push ${{secrets.DOCKER_USERNAME}}/$REPOSITORY:latest

  deploy:
    needs: build-strapi-app
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: build
        run: |
          pwd
          sudo docker compose build
      - name: deploy
        run: |
          sudo docker compose down
          sudo docker compose up -d

      - name: remove image prune
        run: |
          sudo docker image prune --force
